@extends('layouts.app')

@section('title', 'Official Donation Receipt')
@section('page_title', 'Donation Receipt')

@section('content')

<div class="page-header no-print">
    <div>
        <p class="eyebrow">Payment Completed</p>
        <h1>Official Donation Receipt</h1>
        <p class="muted">
            Receipt generated for your completed donation.
        </p>
    </div>

    <div class="toolbar">
        <a href="{{ route('donor.dashboard') }}" class="btn-secondary">
            Back Dashboard
        </a>

        <button onclick="window.print()" class="btn">
            Print / Save PDF
        </button>
    </div>
</div>

<div class="receipt-paper">

    <div class="receipt-top">
        <div class="brand-block">
            <div class="brand-logo">NGO</div>

            <div>
                <h2>NGO Fund Management System</h2>
                <p>Official Donation Receipt</p>
            </div>
        </div>

        <div class="receipt-status">
            <span>PAID</span>
        </div>
    </div>

    <div class="receipt-meta">
        <div>
            <small>Receipt No.</small>
            <strong>{{ $donation->receipt_number ?? '-' }}</strong>
        </div>

        <div>
            <small>Issued Date</small>
            <strong>
                {{ $donation->created_at ? $donation->created_at->format('d M Y, h:i A') : '-' }}
            </strong>
        </div>

        <div>
            <small>Status</small>
            <strong>{{ strtoupper($donation->status ?? '-') }}</strong>
        </div>
    </div>

    <div class="receipt-section">
        <h3>Donation Information</h3>

        <table class="receipt-table">
            <tr>
                <td>Campaign</td>
                <td>{{ $donation->campaign->title ?? 'Campaign Deleted' }}</td>
            </tr>

            <tr>
                <td>Donation Date</td>
                <td>
                    {{ $donation->donation_date ? \Carbon\Carbon::parse($donation->donation_date)->format('d M Y') : '-' }}
                </td>
            </tr>

            <tr>
                <td>Payment Method</td>
                <td>{{ $donation->payment_method ?? '-' }}</td>
            </tr>

            <tr>
                <td>Payment Gateway / Bank</td>
                <td>{{ $donation->payment_gateway ?? '-' }}</td>
            </tr>

            <tr>
                <td>Donation Type</td>
                <td>{{ ucfirst($donation->type ?? 'one-time') }}</td>
            </tr>
        </table>
    </div>

    <div class="amount-box">
        <span>Total Donation Amount</span>
        <strong>RM{{ number_format($donation->amount, 2) }}</strong>
    </div>

    <div class="receipt-section">
        <h3>Verification</h3>

        <div class="verification-grid">
            <div>
                <small>Generated By</small>
                <strong>NGO Fund Management System</strong>
            </div>

            <div>
                <small>Transaction Reference</small>
                <strong>{{ $donation->receipt_number ?? '-' }}</strong>
            </div>
        </div>
    </div>

    <div class="receipt-footer">
        <p>
            This receipt confirms that the donation above has been successfully recorded
            in the NGO Fund Management System.
        </p>

        <div class="signature-row">
            <div>
                <div class="signature-line"></div>
                <strong>System Verified</strong>
                <small>Authorized Receipt</small>
            </div>

            <div class="stamp">
                VERIFIED
            </div>
        </div>
    </div>

</div>

<style>
.receipt-paper {
    max-width: 900px;
    margin: 0 auto;
    background: #ffffff;
    border: 1px solid #d7eadf;
    border-radius: 24px;
    padding: 36px;
    box-shadow: 0 20px 45px rgba(0, 80, 45, 0.10);
    color: #073b2a;
}

.receipt-top {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    border-bottom: 2px solid #d7eadf;
    padding-bottom: 24px;
}

.brand-block {
    display: flex;
    gap: 18px;
    align-items: center;
}

.brand-logo {
    width: 64px;
    height: 64px;
    border-radius: 18px;
    background: #0f7f3f;
    color: white;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 900;
    letter-spacing: 1px;
}

.brand-block h2 {
    margin: 0;
    font-size: 28px;
}

.brand-block p {
    margin: 6px 0 0;
    color: #6b7d72;
}

.receipt-status span {
    display: inline-block;
    padding: 10px 22px;
    border-radius: 999px;
    background: #dcfce7;
    color: #166534;
    font-weight: 900;
    letter-spacing: 1px;
}

.receipt-meta {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 18px;
    margin: 28px 0;
}

.receipt-meta div,
.verification-grid div {
    background: #f6fbf8;
    border: 1px solid #d7eadf;
    border-radius: 18px;
    padding: 18px;
}

.receipt-meta small,
.verification-grid small {
    display: block;
    color: #6b7d72;
    font-weight: 700;
    margin-bottom: 8px;
}

.receipt-meta strong,
.verification-grid strong {
    font-size: 16px;
}

.receipt-section {
    margin-top: 28px;
}

.receipt-section h3 {
    margin: 0 0 14px;
    font-size: 20px;
}

.receipt-table {
    width: 100%;
    border-collapse: collapse;
    overflow: hidden;
    border-radius: 18px;
}

.receipt-table td {
    padding: 16px 18px;
    border-bottom: 1px solid #e1f0e7;
}

.receipt-table tr td:first-child {
    width: 35%;
    background: #f6fbf8;
    font-weight: 800;
    color: #4b6356;
}

.receipt-table tr td:last-child {
    font-weight: 700;
}

.amount-box {
    margin-top: 30px;
    padding: 28px;
    border-radius: 22px;
    background: linear-gradient(135deg, #0f7f3f, #23b26d);
    color: white;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.amount-box span {
    font-weight: 800;
    letter-spacing: 0.5px;
}

.amount-box strong {
    font-size: 36px;
}

.verification-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 18px;
}

.receipt-footer {
    margin-top: 34px;
    border-top: 2px dashed #cfe8d9;
    padding-top: 24px;
}

.receipt-footer p {
    color: #607568;
    line-height: 1.7;
}

.signature-row {
    margin-top: 30px;
    display: flex;
    justify-content: space-between;
    align-items: end;
}

.signature-line {
    width: 220px;
    border-top: 2px solid #073b2a;
    margin-bottom: 10px;
}

.signature-row small {
    display: block;
    color: #6b7d72;
    margin-top: 4px;
}

.stamp {
    width: 130px;
    height: 130px;
    border: 4px solid #16a34a;
    border-radius: 50%;
    color: #16a34a;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 900;
    transform: rotate(-12deg);
    letter-spacing: 2px;
}

@media print {
    .no-print,
    .sidebar,
    .topbar,
    .page-header {
        display: none !important;
    }

    body {
        background: white !important;
    }

    .receipt-paper {
        box-shadow: none;
        border: none;
        margin: 0;
        max-width: 100%;
        border-radius: 0;
    }
}
</style>

@endsection